trigger:
  branches:
    include:
      - main
  paths:
    include:
      - azure-pipelines.yml
      - template.json
      - parameters.json

variables:
  LogicAppName: 'LogicAppName-CI' 
  Location: 'Central India'
  ResourceGroup: 'test-rg01'
  SubscriptionId: 'e62a4643-1777-489d-8615-992e6eb09eda'  # Replace with actual subscription ID

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureServiceConnection'  # Replace with actual name
    subscriptionId: '$(SubscriptionId)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(ResourceGroup)'
    location: '$(Location)'
    templateLocation: 'Linked artifact'
    csmFile: 'template.json'
    csmParametersFile: 'parameters.json'
    deploymentMode: 'Incremental'
